version: "0.5"

processes:
  php-fpm:
    command: php-fpm -y php-fpm.conf --nodaemonize
    availability:
      restart: "on_failure"

  caddy:
    command: caddy run --config Caddyfile
    depends_on:
      php-fpm:
        condition: process_started
