version: "0.5"

processes:
  php-fpm:
    command: bash -c "rm -f ${PHP_SOCKET} && exec php-fpm -y flakeConf/php-fpm.conf --nodaemonize"
    availability:
      restart: "on_failure"

  caddy:
    command: caddy run --config flakeConf/Caddyfile
    depends_on:
      php-fpm:
        condition: process_started
